/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { PluginDTO } from '../models';
import { StringWrapper } from '../models';
/**
 * PluginResourceApi - axios parameter creator
 * @export
 */
export const PluginResourceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getPluginDocumentation
         * @param {string} className className
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPluginDocumentationUsingGET: async (className: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'className' is not null or undefined
            if (className === null || className === undefined) {
                throw new RequiredError('className','Required parameter className was null or undefined when calling getPluginDocumentationUsingGET.');
            }
            const localVarPath = `/api/plugins/{className}/documentation`
                .replace(`{${"className"}}`, encodeURIComponent(String(className)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getPlugin
         * @param {string} className className
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPluginUsingGET: async (className: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'className' is not null or undefined
            if (className === null || className === undefined) {
                throw new RequiredError('className','Required parameter className was null or undefined when calling getPluginUsingGET.');
            }
            const localVarPath = `/api/plugins/{className}`
                .replace(`{${"className"}}`, encodeURIComponent(String(className)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getPlugins
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPluginsUsingGET: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/plugins`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PluginResourceApi - functional programming interface
 * @export
 */
export const PluginResourceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary getPluginDocumentation
         * @param {string} className className
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPluginDocumentationUsingGET(className: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StringWrapper>> {
            const localVarAxiosArgs = await PluginResourceApiAxiosParamCreator(configuration).getPluginDocumentationUsingGET(className, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary getPlugin
         * @param {string} className className
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPluginUsingGET(className: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PluginDTO>> {
            const localVarAxiosArgs = await PluginResourceApiAxiosParamCreator(configuration).getPluginUsingGET(className, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary getPlugins
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPluginsUsingGET(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PluginDTO>>> {
            const localVarAxiosArgs = await PluginResourceApiAxiosParamCreator(configuration).getPluginsUsingGET(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * PluginResourceApi - factory interface
 * @export
 */
export const PluginResourceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary getPluginDocumentation
         * @param {string} className className
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPluginDocumentationUsingGET(className: string, options?: any): AxiosPromise<StringWrapper> {
            return PluginResourceApiFp(configuration).getPluginDocumentationUsingGET(className, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getPlugin
         * @param {string} className className
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPluginUsingGET(className: string, options?: any): AxiosPromise<PluginDTO> {
            return PluginResourceApiFp(configuration).getPluginUsingGET(className, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getPlugins
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPluginsUsingGET(options?: any): AxiosPromise<Array<PluginDTO>> {
            return PluginResourceApiFp(configuration).getPluginsUsingGET(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PluginResourceApi - object-oriented interface
 * @export
 * @class PluginResourceApi
 * @extends {BaseAPI}
 */
export class PluginResourceApi extends BaseAPI {
    /**
     * 
     * @summary getPluginDocumentation
     * @param {string} className className
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PluginResourceApi
     */
    public getPluginDocumentationUsingGET(className: string, options?: any) {
        return PluginResourceApiFp(this.configuration).getPluginDocumentationUsingGET(className, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary getPlugin
     * @param {string} className className
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PluginResourceApi
     */
    public getPluginUsingGET(className: string, options?: any) {
        return PluginResourceApiFp(this.configuration).getPluginUsingGET(className, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary getPlugins
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PluginResourceApi
     */
    public getPluginsUsingGET(options?: any) {
        return PluginResourceApiFp(this.configuration).getPluginsUsingGET(options).then((request) => request(this.axios, this.basePath));
    }
}
