/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ProcessingChainDTO } from '../models';
/**
 * ProcessingChainResourceApi - axios parameter creator
 * @export
 */
export const ProcessingChainResourceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary createProcessingChain
         * @param {ProcessingChainDTO} body processingChainDTO
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProcessingChainUsingPOST: async (body: ProcessingChainDTO, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createProcessingChainUsingPOST.');
            }
            const localVarPath = `/api/processing-chains`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary deleteProcessingChainStep
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProcessingChainStepUsingDELETE: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling deleteProcessingChainStepUsingDELETE.');
            }
            const localVarPath = `/api/processing-chains/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getProcessingChainSteps
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProcessingChainStepsUsingGET: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getProcessingChainStepsUsingGET.');
            }
            const localVarPath = `/api/processing-chains/{id}/steps`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getProcessingChain
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProcessingChainUsingGET: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getProcessingChainUsingGET.');
            }
            const localVarPath = `/api/processing-chains/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getProcessingChains
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProcessingChainsUsingGET: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/processing-chains`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary updateProcessingChain
         * @param {ProcessingChainDTO} body processingChainDTO
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProcessingChainUsingPUT: async (body: ProcessingChainDTO, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateProcessingChainUsingPUT.');
            }
            const localVarPath = `/api/processing-chains`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProcessingChainResourceApi - functional programming interface
 * @export
 */
export const ProcessingChainResourceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary createProcessingChain
         * @param {ProcessingChainDTO} body processingChainDTO
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProcessingChainUsingPOST(body: ProcessingChainDTO, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProcessingChainDTO>> {
            const localVarAxiosArgs = await ProcessingChainResourceApiAxiosParamCreator(configuration).createProcessingChainUsingPOST(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary deleteProcessingChainStep
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProcessingChainStepUsingDELETE(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await ProcessingChainResourceApiAxiosParamCreator(configuration).deleteProcessingChainStepUsingDELETE(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary getProcessingChainSteps
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProcessingChainStepsUsingGET(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProcessingChainDTO>>> {
            const localVarAxiosArgs = await ProcessingChainResourceApiAxiosParamCreator(configuration).getProcessingChainStepsUsingGET(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary getProcessingChain
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProcessingChainUsingGET(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProcessingChainDTO>> {
            const localVarAxiosArgs = await ProcessingChainResourceApiAxiosParamCreator(configuration).getProcessingChainUsingGET(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary getProcessingChains
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProcessingChainsUsingGET(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProcessingChainDTO>>> {
            const localVarAxiosArgs = await ProcessingChainResourceApiAxiosParamCreator(configuration).getProcessingChainsUsingGET(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary updateProcessingChain
         * @param {ProcessingChainDTO} body processingChainDTO
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProcessingChainUsingPUT(body: ProcessingChainDTO, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProcessingChainDTO>> {
            const localVarAxiosArgs = await ProcessingChainResourceApiAxiosParamCreator(configuration).updateProcessingChainUsingPUT(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ProcessingChainResourceApi - factory interface
 * @export
 */
export const ProcessingChainResourceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary createProcessingChain
         * @param {ProcessingChainDTO} body processingChainDTO
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProcessingChainUsingPOST(body: ProcessingChainDTO, options?: any): AxiosPromise<ProcessingChainDTO> {
            return ProcessingChainResourceApiFp(configuration).createProcessingChainUsingPOST(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary deleteProcessingChainStep
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProcessingChainStepUsingDELETE(id: number, options?: any): AxiosPromise<void> {
            return ProcessingChainResourceApiFp(configuration).deleteProcessingChainStepUsingDELETE(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getProcessingChainSteps
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProcessingChainStepsUsingGET(id: number, options?: any): AxiosPromise<Array<ProcessingChainDTO>> {
            return ProcessingChainResourceApiFp(configuration).getProcessingChainStepsUsingGET(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getProcessingChain
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProcessingChainUsingGET(id: number, options?: any): AxiosPromise<ProcessingChainDTO> {
            return ProcessingChainResourceApiFp(configuration).getProcessingChainUsingGET(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getProcessingChains
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProcessingChainsUsingGET(options?: any): AxiosPromise<Array<ProcessingChainDTO>> {
            return ProcessingChainResourceApiFp(configuration).getProcessingChainsUsingGET(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary updateProcessingChain
         * @param {ProcessingChainDTO} body processingChainDTO
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProcessingChainUsingPUT(body: ProcessingChainDTO, options?: any): AxiosPromise<ProcessingChainDTO> {
            return ProcessingChainResourceApiFp(configuration).updateProcessingChainUsingPUT(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProcessingChainResourceApi - object-oriented interface
 * @export
 * @class ProcessingChainResourceApi
 * @extends {BaseAPI}
 */
export class ProcessingChainResourceApi extends BaseAPI {
    /**
     * 
     * @summary createProcessingChain
     * @param {ProcessingChainDTO} body processingChainDTO
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessingChainResourceApi
     */
    public createProcessingChainUsingPOST(body: ProcessingChainDTO, options?: any) {
        return ProcessingChainResourceApiFp(this.configuration).createProcessingChainUsingPOST(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary deleteProcessingChainStep
     * @param {number} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessingChainResourceApi
     */
    public deleteProcessingChainStepUsingDELETE(id: number, options?: any) {
        return ProcessingChainResourceApiFp(this.configuration).deleteProcessingChainStepUsingDELETE(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary getProcessingChainSteps
     * @param {number} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessingChainResourceApi
     */
    public getProcessingChainStepsUsingGET(id: number, options?: any) {
        return ProcessingChainResourceApiFp(this.configuration).getProcessingChainStepsUsingGET(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary getProcessingChain
     * @param {number} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessingChainResourceApi
     */
    public getProcessingChainUsingGET(id: number, options?: any) {
        return ProcessingChainResourceApiFp(this.configuration).getProcessingChainUsingGET(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary getProcessingChains
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessingChainResourceApi
     */
    public getProcessingChainsUsingGET(options?: any) {
        return ProcessingChainResourceApiFp(this.configuration).getProcessingChainsUsingGET(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary updateProcessingChain
     * @param {ProcessingChainDTO} body processingChainDTO
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProcessingChainResourceApi
     */
    public updateProcessingChainUsingPUT(body: ProcessingChainDTO, options?: any) {
        return ProcessingChainResourceApiFp(this.configuration).updateProcessingChainUsingPUT(body, options).then((request) => request(this.axios, this.basePath));
    }
}
