/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DeviceDTO } from '../models';
import { SpaceDTO } from '../models';
/**
 * SpaceResourceApi - axios parameter creator
 * @export
 */
export const SpaceResourceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary createSpace
         * @param {SpaceDTO} body space
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSpaceUsingPOST: async (body: SpaceDTO, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createSpaceUsingPOST.');
            }
            const localVarPath = `/api/spaces`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary deleteSpace
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSpaceUsingDELETE: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling deleteSpaceUsingDELETE.');
            }
            const localVarPath = `/api/spaces/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getDevicesBelongingToSpace
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDevicesBelongingToSpaceUsingGET: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getDevicesBelongingToSpaceUsingGET.');
            }
            const localVarPath = `/api/spaces/{id}/devices`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getSpace
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpaceUsingGET: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getSpaceUsingGET.');
            }
            const localVarPath = `/api/spaces/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getSpacesBelongingToSpace
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpacesBelongingToSpaceUsingGET: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getSpacesBelongingToSpaceUsingGET.');
            }
            const localVarPath = `/api/spaces/{id}/spaces`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary getSpaces
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpacesUsingGET: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/spaces`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary updateSpace
         * @param {SpaceDTO} body space
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSpaceUsingPUT: async (body: SpaceDTO, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateSpaceUsingPUT.');
            }
            const localVarPath = `/api/spaces`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SpaceResourceApi - functional programming interface
 * @export
 */
export const SpaceResourceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary createSpace
         * @param {SpaceDTO} body space
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSpaceUsingPOST(body: SpaceDTO, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SpaceDTO>> {
            const localVarAxiosArgs = await SpaceResourceApiAxiosParamCreator(configuration).createSpaceUsingPOST(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary deleteSpace
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSpaceUsingDELETE(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await SpaceResourceApiAxiosParamCreator(configuration).deleteSpaceUsingDELETE(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary getDevicesBelongingToSpace
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDevicesBelongingToSpaceUsingGET(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DeviceDTO>>> {
            const localVarAxiosArgs = await SpaceResourceApiAxiosParamCreator(configuration).getDevicesBelongingToSpaceUsingGET(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary getSpace
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSpaceUsingGET(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SpaceDTO>> {
            const localVarAxiosArgs = await SpaceResourceApiAxiosParamCreator(configuration).getSpaceUsingGET(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary getSpacesBelongingToSpace
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSpacesBelongingToSpaceUsingGET(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SpaceDTO>>> {
            const localVarAxiosArgs = await SpaceResourceApiAxiosParamCreator(configuration).getSpacesBelongingToSpaceUsingGET(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary getSpaces
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSpacesUsingGET(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SpaceDTO>>> {
            const localVarAxiosArgs = await SpaceResourceApiAxiosParamCreator(configuration).getSpacesUsingGET(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary updateSpace
         * @param {SpaceDTO} body space
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSpaceUsingPUT(body: SpaceDTO, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SpaceDTO>> {
            const localVarAxiosArgs = await SpaceResourceApiAxiosParamCreator(configuration).updateSpaceUsingPUT(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SpaceResourceApi - factory interface
 * @export
 */
export const SpaceResourceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary createSpace
         * @param {SpaceDTO} body space
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSpaceUsingPOST(body: SpaceDTO, options?: any): AxiosPromise<SpaceDTO> {
            return SpaceResourceApiFp(configuration).createSpaceUsingPOST(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary deleteSpace
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSpaceUsingDELETE(id: number, options?: any): AxiosPromise<void> {
            return SpaceResourceApiFp(configuration).deleteSpaceUsingDELETE(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getDevicesBelongingToSpace
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDevicesBelongingToSpaceUsingGET(id: number, options?: any): AxiosPromise<Array<DeviceDTO>> {
            return SpaceResourceApiFp(configuration).getDevicesBelongingToSpaceUsingGET(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getSpace
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpaceUsingGET(id: number, options?: any): AxiosPromise<SpaceDTO> {
            return SpaceResourceApiFp(configuration).getSpaceUsingGET(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getSpacesBelongingToSpace
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpacesBelongingToSpaceUsingGET(id: number, options?: any): AxiosPromise<Array<SpaceDTO>> {
            return SpaceResourceApiFp(configuration).getSpacesBelongingToSpaceUsingGET(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary getSpaces
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpacesUsingGET(options?: any): AxiosPromise<Array<SpaceDTO>> {
            return SpaceResourceApiFp(configuration).getSpacesUsingGET(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary updateSpace
         * @param {SpaceDTO} body space
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSpaceUsingPUT(body: SpaceDTO, options?: any): AxiosPromise<SpaceDTO> {
            return SpaceResourceApiFp(configuration).updateSpaceUsingPUT(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SpaceResourceApi - object-oriented interface
 * @export
 * @class SpaceResourceApi
 * @extends {BaseAPI}
 */
export class SpaceResourceApi extends BaseAPI {
    /**
     * 
     * @summary createSpace
     * @param {SpaceDTO} body space
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpaceResourceApi
     */
    public createSpaceUsingPOST(body: SpaceDTO, options?: any) {
        return SpaceResourceApiFp(this.configuration).createSpaceUsingPOST(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary deleteSpace
     * @param {number} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpaceResourceApi
     */
    public deleteSpaceUsingDELETE(id: number, options?: any) {
        return SpaceResourceApiFp(this.configuration).deleteSpaceUsingDELETE(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary getDevicesBelongingToSpace
     * @param {number} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpaceResourceApi
     */
    public getDevicesBelongingToSpaceUsingGET(id: number, options?: any) {
        return SpaceResourceApiFp(this.configuration).getDevicesBelongingToSpaceUsingGET(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary getSpace
     * @param {number} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpaceResourceApi
     */
    public getSpaceUsingGET(id: number, options?: any) {
        return SpaceResourceApiFp(this.configuration).getSpaceUsingGET(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary getSpacesBelongingToSpace
     * @param {number} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpaceResourceApi
     */
    public getSpacesBelongingToSpaceUsingGET(id: number, options?: any) {
        return SpaceResourceApiFp(this.configuration).getSpacesBelongingToSpaceUsingGET(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary getSpaces
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpaceResourceApi
     */
    public getSpacesUsingGET(options?: any) {
        return SpaceResourceApiFp(this.configuration).getSpacesUsingGET(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary updateSpace
     * @param {SpaceDTO} body space
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpaceResourceApi
     */
    public updateSpaceUsingPUT(body: SpaceDTO, options?: any) {
        return SpaceResourceApiFp(this.configuration).updateSpaceUsingPUT(body, options).then((request) => request(this.axios, this.basePath));
    }
}
