/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceDTO
 */
export interface DeviceDTO {
    /**
     * 
     * @type {string}
     * @memberof DeviceDTO
     */
    externalId?: string;
    /**
     * 
     * @type {number}
     * @memberof DeviceDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DeviceDTO
     */
    lastSentMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceDTO
     */
    slug?: string;
    /**
     * 
     * @type {number}
     * @memberof DeviceDTO
     */
    spaceId?: number;
}

export function DeviceDTOFromJSON(json: any): DeviceDTO {
    return DeviceDTOFromJSONTyped(json, false);
}

export function DeviceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'externalId': !exists(json, 'externalId') ? undefined : json['externalId'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'lastSentMessage': !exists(json, 'lastSentMessage') ? undefined : json['lastSentMessage'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'spaceId': !exists(json, 'spaceId') ? undefined : json['spaceId'],
    };
}

export function DeviceDTOToJSON(value?: DeviceDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'externalId': value.externalId,
        'id': value.id,
        'lastSentMessage': value.lastSentMessage,
        'name': value.name,
        'slug': value.slug,
        'spaceId': value.spaceId,
    };
}


