/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DeviceDTO
 */
export interface DeviceDTO {
    /**
     * 
     * @type {string}
     * @memberof DeviceDTO
     */
    externalId?: any;
    /**
     * 
     * @type {number}
     * @memberof DeviceDTO
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof DeviceDTO
     */
    lastSentMessage?: any;
    /**
     * 
     * @type {string}
     * @memberof DeviceDTO
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof DeviceDTO
     */
    slug?: any;
    /**
     * 
     * @type {number}
     * @memberof DeviceDTO
     */
    spaceId?: any;
}
