/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PluginDTO
 */
export interface PluginDTO {
    /**
     * 
     * @type {string}
     * @memberof PluginDTO
     */
    className?: string;
    /**
     * 
     * @type {string}
     * @memberof PluginDTO
     */
    displayName?: string;
}

export function PluginDTOFromJSON(json: any): PluginDTO {
    return PluginDTOFromJSONTyped(json, false);
}

export function PluginDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'className': !exists(json, 'className') ? undefined : json['className'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
    };
}

export function PluginDTOToJSON(value?: PluginDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'className': value.className,
        'displayName': value.displayName,
    };
}


