/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProcessingChainDTO
 */
export interface ProcessingChainDTO {
    /**
     * 
     * @type {number}
     * @memberof ProcessingChainDTO
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof ProcessingChainDTO
     */
    inputDeviceId?: any;
    /**
     * 
     * @type {number}
     * @memberof ProcessingChainDTO
     */
    nextId?: any;
    /**
     * 
     * @type {number}
     * @memberof ProcessingChainDTO
     */
    outputDeviceId?: any;
    /**
     * 
     * @type {number}
     * @memberof ProcessingChainDTO
     */
    signalProcessorId?: any;
}
