/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SignalProcessorDTO
 */
export interface SignalProcessorDTO {
    /**
     * 
     * @type {string}
     * @memberof SignalProcessorDTO
     */
    className?: any;
    /**
     * 
     * @type {string}
     * @memberof SignalProcessorDTO
     */
    configuration?: any;
    /**
     * 
     * @type {number}
     * @memberof SignalProcessorDTO
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof SignalProcessorDTO
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof SignalProcessorDTO
     */
    state?: any;
    /**
     * 
     * @type {string}
     * @memberof SignalProcessorDTO
     */
    status?: any;
}
