/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignalProcessorDTO
 */
export interface SignalProcessorDTO {
    /**
     * 
     * @type {string}
     * @memberof SignalProcessorDTO
     */
    className?: string;
    /**
     * 
     * @type {string}
     * @memberof SignalProcessorDTO
     */
    _configuration?: string;
    /**
     * 
     * @type {number}
     * @memberof SignalProcessorDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SignalProcessorDTO
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof SignalProcessorDTO
     */
    spaceId?: number;
    /**
     * 
     * @type {string}
     * @memberof SignalProcessorDTO
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof SignalProcessorDTO
     */
    status?: string;
}

export function SignalProcessorDTOFromJSON(json: any): SignalProcessorDTO {
    return SignalProcessorDTOFromJSONTyped(json, false);
}

export function SignalProcessorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignalProcessorDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'className': !exists(json, 'className') ? undefined : json['className'],
        '_configuration': !exists(json, 'configuration') ? undefined : json['configuration'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'spaceId': !exists(json, 'spaceId') ? undefined : json['spaceId'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function SignalProcessorDTOToJSON(value?: SignalProcessorDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'className': value.className,
        'configuration': value._configuration,
        'id': value.id,
        'name': value.name,
        'spaceId': value.spaceId,
        'state': value.state,
        'status': value.status,
    };
}


